# Generated by Django 4.0.5 on 2022-06-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdetails',
            options={'verbose_name': 'Stock Details'},
        ),
    ]
